GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
ALTER DEFAULT PRIVILEGES FOR USER CURRENT_USER IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO admin;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO admin;